CREATE TABLE FLUJO(
    FLUJO CHAR(10),
    PROCESO CHAR(10),
    PROCESO_SIG CHAR(10),
    TIPO CHAR(50),
    ROL VARCHAR(60),
    PANTALLA CHAR(100)
);

INSERT INTO FLUJO VALUES ('F1', 'P1', 'P2', 'I', 'ESTUDIANTE', 'PRE-INSCRIPCION'); 
INSERT INTO FLUJO VALUES ('F1', 'P2', 'P3', 'P', 'KARDEX', 'RECEPCIÓN-FORM'); 
INSERT INTO FLUJO VALUES ('F1', 'P3', 'P4', 'P', 'KARDEX', 'HORARIOS'); 
INSERT INTO FLUJO VALUES ('F1', 'P4', '', 'C', 'ESTUDIANTE', 'MATERIAS-DISP');
INSERT INTO FLUJO VALUES ('F1', 'P5', '', 'F', 'ESTUDIANTE', 'CANCELAR'); 
INSERT INTO FLUJO VALUES ('F1', 'P6', 'P7', 'P', 'ESTUDIANTE', 'SOLICITAR-COD'); 
INSERT INTO FLUJO VALUES ('F1', 'P7', 'P8', 'P', 'KARDEX', 'GENERAR-COD'); 
INSERT INTO FLUJO VALUES ('F1', 'P8', 'P9', 'P', 'KARDEX', 'CONTAR-MAT'); 
INSERT INTO FLUJO VALUES ('F1', 'P9', 'P10', 'P', 'ESTUDIANTE', 'SELECCIÓN-MAT'); 
INSERT INTO FLUJO VALUES ('F1', 'P10', '', 'F', 'CENTRO ESTUDIANTES', 'VERIFICAR-DOC'); 

CREATE TABLE FLUJO_COND(
    FLUJO CHAR(10),
    PROCESO CHAR(10),
    PROCESO_SI CHAR(10),
    PROCESO_NO CHAR(10)
);

INSERT INTO FLUJO_COND VALUES ('F1', 'P4', 'P6', 'P5'); 


CREATE TABLE FLUJO_INSC(
    FLUJO CHAR(10),
    PROCESO CHAR(10),
    NRO_INSC INT,
    FECHA_INI DATE,
    FECHA_FIN DATE,
    USER CHAR(30)
);

INSERT INTO FLUJO_INSC VALUES ('F1', 'P1', 100, '2023-06-07', '', 'EST@654'); 
INSERT INTO FLUJO_INSC VALUES ('F1', 'P4', 100, '2023-06-08', '', 'SSA@UNO'); 
INSERT INTO FLUJO_INSC VALUES ('F1', 'P10', 100, '2023-06-09', '', 'CD@DOS'); 

